export const expectedDefMap = {
  accessControl: {
    groupname: "OgcApiDataV2",
    title: "accessControl",
    description: "[Access Control](#access-control) configuration.",
    ref: "ApiSecurity",
    addRef: "",
    deprecated: false,
  },
  api: {
    groupname: "OgcApiDataV2",
    title: "api",
    description: "[API Building Blocks](#building-blocks) configuration.",
    ref: "ExtensionConfiguration",
    addRef: "",
    deprecated: false,
  },
  apiValidation: {
    groupname: "OgcApiDataV2",
    title: "apiValidation",
    description:
      "During startup of an API, the configuration can be validated. The supported values are     `NONE`, `LAX`, and `STRICT`. `STRICT` will block the start of an API with warnings, while     an API with warnings, but no errors will start with `LAX`. If the value is set to `NONE`,     no validation will occur. Warnings are issued for problems in the configuration that can     affect the use of the API while errors are issued for cases where the API cannot be used.     Typically, API validation during startup will only be used in development and testing     environments since the API validating results in a slower startup time and should not be     necessary in production environments.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  apiVersion: {
    groupname: "OgcApiDataV2",
    title: "apiVersion",
    description:
      "Adds a version to the URL path, instead of `/{id}` it will be `/{id}/v{apiVersion}`.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  asQueryParameters: {
    groupname: "QueryablesConfiguration",
    title: "asQueryParameters",
    description:
      "If `true`, all queryables with a simple value (string, number or boolean) will be     provided query parameters to filter features.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  auto: {
    groupname: "OgcApiDataV2",
    title: "auto",
    description: "Option to generate missing definitions automatically from the data source.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  autoPersist: {
    groupname: "OgcApiDataV2",
    title: "autoPersist",
    description:
      "Option to persist definitions generated with `auto` to the configuration file. The     [Store](/application/40-store.md) must not be `READ_ONLY` for this to take effect.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  buildingBlock: {
    groupname: "QueryablesConfiguration",
    title: "buildingBlock",
    description: "Always `QUERYABLES`.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  caching: {
    groupname: "QueryablesConfiguration",
    title: "caching",
    description:
      "Sets fixed values for [HTTP Caching Headers](/services/README.md#caching) for the     resources.",
    ref: "Caching",
    addRef: "",
    deprecated: false,
  },
  collections: {
    groupname: "OgcApiDataV2",
    title: "collections",
    description:
      "Collection configurations, the key is the collection id, for the value see     [Collection](#collection) below.",
    ref: "",
    addRef: "FeatureTypeConfigurationOgcApi",
    deprecated: false,
  },
  createdAt: {
    groupname: "OgcApiDataV2",
    title: "createdAt",
    description: "",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  defaultCaching: {
    groupname: "OgcApiDataV2",
    title: "defaultCaching",
    description: "Sets fixed values for [HTTP Caching Headers](#caching) for the resources.",
    ref: "Caching",
    addRef: "",
    deprecated: false,
  },
  defaultExtent: {
    groupname: "OgcApiDataV2",
    title: "defaultExtent",
    description:
      "By default, the spatial and temporal extent of data is derived from the data when     starting the API, but the [Default Extent](#default-extent) can also be configured.",
    ref: "CollectionExtent",
    addRef: "",
    deprecated: false,
  },
  description: {
    groupname: "OgcApiDataV2",
    title: "description",
    description: "Human readable description.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  enableEndpoint: {
    groupname: "QueryablesConfiguration",
    title: "enableEndpoint",
    description: "If `true`, the Queryables endpoint will be enabled.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  enabled: {
    groupname: "OgcApiDataV2",
    title: "enabled",
    description:
      "Option to disable the service, which means its REST API will not be available and     background tasks will not be running.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  enabled1: {
    groupname: "QueryablesConfiguration",
    title: "enabled",
    description: "Enable the building block?",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  entityStorageVersion: {
    groupname: "OgcApiDataV2",
    title: "entityStorageVersion",
    description: "",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  excluded: {
    groupname: "QueryablesConfiguration",
    title: "excluded",
    description:
      "The list of properties that would be queryables based on `included`, but which should     not be queryables.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  extensionType: {
    groupname: "QueryablesConfiguration",
    title: "extensionType",
    description: "*Deprecated* See `buildingBlock`.",
    ref: "",
    addRef: "",
    deprecated: true,
  },
  externalDocs: {
    groupname: "OgcApiDataV2",
    title: "externalDocs",
    description:
      "Link to a [document or website](#external-document) with more information about this     API.",
    ref: "ExternalDocumentation",
    addRef: "",
    deprecated: false,
  },
  id: {
    groupname: "OgcApiDataV2",
    title: "id",
    description:
      "Unique identifier of the entity, has to match the filename. Allowed characters are     (A-Z, a-z), numbers (0-9), underscore and hyphen.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  included: {
    groupname: "QueryablesConfiguration",
    title: "included",
    description:
      "The list of properties that can be used in CQL2 filter expressions and/or for which     filtering query parameters are provided for a collection. Properties that are not of type     `OBJECT` or `OBJECT_ARRAY` are eligible as queryables unless `isQueryable` is set to     `false` for the property. The special value `*` includes all eligible properties as     queryables. By default, no property is queryable (this is for backwards compatibility, in     v4.0 the default behaviour will change to all eligible properties).",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  label: {
    groupname: "OgcApiDataV2",
    title: "label",
    description: "Human readable label.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  lastModified: {
    groupname: "OgcApiDataV2",
    title: "lastModified",
    description: "",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  metadata: {
    groupname: "OgcApiDataV2",
    title: "metadata",
    description: "General [Metadata](#metadata) for the API.",
    ref: "ApiMetadata",
    addRef: "",
    deprecated: false,
  },
  pathSeparator: {
    groupname: "QueryablesConfiguration",
    title: "pathSeparator",
    description:
      "The character that is used as the path separator in case of object-valued properties.     Either `DOT` or `UNDERSCORE`.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  serviceType: {
    groupname: "OgcApiDataV2",
    title: "serviceType",
    description: "Always `OGC_API`.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
  shouldStart: {
    groupname: "OgcApiDataV2",
    title: "shouldStart",
    description: "*Deprecated* See `enabled`.",
    ref: "",
    addRef: "",
    deprecated: true,
  },
  tags: {
    groupname: "OgcApiDataV2",
    title: "tags",
    description:
      "Tags for this API. Every tag is a string without white space. Tags are shown in the     *API Catalog* and can be used to filter the catalog response with the query parameter     `tags`, e.g. `tags\u003dINSPIRE`.",
    ref: "",
    addRef: "",
    deprecated: false,
  },
};
