when:
  event: [push, tag]

matrix:
  PLATFORM:
    - darwin-arm64
    - linux-arm64
    - linux-x64

steps:
  native:
    image: node:20-alpine
    environment:
      VSIX_PLATFORM: ${PLATFORM}
    commands:
      - npm run install:all
      - npm run package:native
