when:
  event: tag

depends_on:
  - build

steps:
  download:
    image: alpine/curl
    commands:
      - mkdir -p dist/vsix
      - curl --verbose -O --output-dir dist/vsix https://dl.interactive-instruments.de/repository/ldproxy/editor/${CI_COMMIT_TAG}/ldproxy-editor-darwin-arm64-${CI_COMMIT_TAG}.vsix
      - curl --verbose -O --output-dir dist/vsix https://dl.interactive-instruments.de/repository/ldproxy/editor/${CI_COMMIT_TAG}/ldproxy-editor-linux-arm64-${CI_COMMIT_TAG}.vsix
      - curl --verbose -O --output-dir dist/vsix https://dl.interactive-instruments.de/repository/ldproxy/editor/${CI_COMMIT_TAG}/ldproxy-editor-linux-x64-${CI_COMMIT_TAG}.vsix
      - ls -la dist/vsix

  publish:
    image: node:20-alpine
    environment:
      VSCE_PAT:
        from_secret: vscode_marketplace_token
    commands:
      - npm ci --ignore-scripts
      - npm run publish

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/editor
      auto_tag: true
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
