when:
  event: push

steps:
  native:
    image: node:20-alpine
    commands:
      - npm run install:all
      - npm test
      - npm run package:native

  nexus:
    image: rockdrilla/woodpecker-sonatype-nexus
    settings:
      nexus_url: https://dl.interactive-instruments.de
      auth_base64:
        from_secret: nexus_auth_b64
      upload: '[{"repository": "ldproxy", "paths": ["dist/vsix/*.vsix"], "directory": "/editor/"}]'
  #        - repository: ldproxy
  #          directory: /editor/
  #          paths:
  #            - dist/vsix/*.vsix

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/editor
      tags: next
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64
        #- linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
